export const sprites = [
  {
    id: 1,
    name: "Sora",
    franchise: "Kingdom Hearts",
    path: "/pixels/sora-attacking.gif",
    width: 340,
    height: 340,
    displaySize: 120,
  },
  {
    id: 2,
    name: "Illidan",
    franchise: "World of Warcraft",
    path: "/pixels/illidan.gif",
    width: 250,
    height: 250,
    displaySize: 120,
  },
  {
    id: 3,
    name: "Satoru Gojo",
    franchise: "Jujutsu Kaisen",
    path: "/pixels/gojo.gif",
    width: 300,
    height: 300,
    displaySize: 130,
  },
  {
    id: 4,
    name: "Darth Vader",
    franchise: "Star Wars",
    path: "/pixels/vader-deflecting.gif",
    width: 320,
    height: 300,
    displaySize: 130,
  },
  {
    id: 5,
    name: "The Flash",
    franchise: "DC Comics",
    path: "/pixels/the-flash.gif",
    width: 250,
    height: 250,
    displaySize: 120,
  },
  {
    id: 6,
    name: "Ichigo",
    franchise: "Bleach",
    path: "/pixels/ichigo.gif",
    width: 300,
    height: 300,
    displaySize: 130,
  },
  {
    id: 7,
    name: "Katarina",
    franchise: "League of Legends",
    path: "/pixels/katarina.gif",
    width: 250,
    height: 200,
    displaySize: 70,
  },
  {
    id: 8,
    name: "Spider-Man",
    franchise: "Marvel",
    path: "/pixels/spiderman.gif",
    width: 250,
    height: 250,
    displaySize: 70,
  },
  {
    id: 9,
    name: "Goku",
    franchise: "Dragon Ball",
    path: "/pixels/ui-goku.gif",
    width: 320,
    height: 320,
    displaySize: 160,
  },
  {
    id: 10,
    name: "Ryu",
    franchise: "Street Fighter",
    path: "/pixels/ryu-hadouken.gif",
    width: 300,
    height: 150,
    displaySize: 70,
  },
  {
    id: 11,
    name: "Banana",
    franchise: "Banana",
    path: "/pixels/banana.gif",
    width: 150,
    height: 150,
    displaySize: 70,
  },
  {
    id: 12,
    name: "Cat",
    franchise: "Cat",
    path: "/pixels/cat.gif",
    width: 150,
    height: 150,
    displaySize: 70,
  }
];
